//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tender.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string INN { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public int TenderId { get; set; }
        public int ParticipantId { get; set; }
        public int StatusId { get; set; }
        public string Condition { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual Tenders Tenders { get; set; }
    }
}
