//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tender.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenders
    {
        public int Id { get; set; }
        public int OrganizerId { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public System.DateTime DateOfEnd { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
